# Generated by Django 4.1.4 on 2022-12-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_user_password'),
        ('notas', '0004_alter_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='deadline',
            field=models.DateTimeField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.user'),
        ),
    ]
