# Generated by Django 4.1.4 on 2022-12-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_alter_notes_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='beginning',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de inicio'),
        ),
    ]
